#!/bin/bash

## Description: Delegates commands to the contao console
## Usage: console
## Example: "ddev console contao:migrate"

ddev exec -d /var/www/html/.ddev/contao vendor/bin/contao-console "$@"
